export const DEFAULT_LANGUAGE_CODE = 'en-US'

export const LANGUAGES = {
  'en-US': 'English (US) (en-US)',
  af: 'Afrikaans (af)',
  ar: 'عربي (ar)',
  az: 'Azərbaycanca (az)',
  bg: 'Български (bg)',
  bm: 'Bamanankan (bm)',
  'bn-BD': 'বাংলা (বাংলাদেশ) (bn-BD)',
  'bn-IN': 'বাংলা (ভারত) (bn-IN)',
  ca: 'Català (ca)',
  cs: 'Čeština (cs)',
  de: 'Deutsch (de)',
  ee: 'Eʋe (ee)',
  el: 'Ελληνικά (el)',
  es: 'Español (es)',
  fa: 'فارسی (fa)',
  ff: 'Pulaar-Fulfulde (ff)',
  fi: 'suomi (fi)',
  fr: 'Français (fr)',
  'fy-NL': 'Frysk (fy-NL)',
  'ga-IE': 'Gaeilge (ga-IE)',
  ha: 'Hausa (ha)',
  he: 'עברית (he)',
  'hi-IN': 'हिन्दी (भारत) (hi-IN)',
  hr: 'Hrvatski (hr)',
  hu: 'magyar (hu)',
  id: 'Bahasa Indonesia (id)',
  ig: 'Igbo (ig)',
  it: 'Italiano (it)',
  ja: '日本語 (ja)',
  ka: 'ქართული (ka)',
  kab: 'Taqbaylit (kab)',
  ko: '한국어 (ko)',
  ln: 'Lingála (ln)',
  mg: 'Malagasy (mg)',
  ml: 'മലയാളം (ml)',
  ms: 'Melayu (ms)',
  my: 'မြန်မာဘာသာ (my)',
  nl: 'Nederlands (nl)',
  pl: 'Polski (pl)',
  'pt-BR': 'Português (do Brasil) (pt-BR)',
  'pt-PT': 'Português (Europeu) (pt-PT)',
  ro: 'Română (ro)',
  ru: 'Русский (ru)',
  son: 'Soŋay (son)',
  sq: 'Shqip (sq)',
  sr: 'Српски (sr)',
  'sr-Latn': 'Srpski (sr-Latn)',
  'sv-SE': 'Svenska (sv-SE)',
  sw: 'Kiswahili (sw)',
  ta: 'தமிழ் (ta)',
  te: 'తెలుగు (te)',
  th: 'ไทย (th)',
  tl: 'Tagalog (tl)',
  tn: 'Setswana (tn)',
  tr: 'Türkçe (tr)',
  uk: 'Українська (uk)',
  vi: 'Tiếng Việt (vi)',
  wo: 'Wolof (wo)',
  xh: 'isiXhosa (xh)',
  yo: 'Yorùbá (yo)',
  'zh-CN': '中文 (简体) (zh-CN)',
  'zh-TW': '正體中文 (繁體) (zh-TW)',
  zu: 'isiZulu (zu)'
}
